### ISSUE TITLE
include usb-modeswitch in default install

### ISSUE THREAD

**Issue by pravi** [RPi-Distro/pi-gen#1]
This is required to get usb dongles internet devises like Tata Photon working.

http://www.tataphoton.com/photon-max-wifi.aspx its a very common method to get internet connection in India. It is included in desktop images of debian.

**Comment by XECDesign** [comment]
Fixed by bdca3e3b48e72df796ec7b1a24a26c08b2dcfa67. In the future, this may move out of the lite image into the desktop only.
