### ISSUE TITLE
It's running but afterwards

### ISSUE THREAD

**Issue by saytinh** [RPi-Distro/pi-gen#111]
Hi,

I'm a really new bible and want to try with it and have maybe a silly question.

Finally, I've done all and it's running now. But how I config like adding my wallet to mining Ethereum? Thanks

**Comment by Landrash** [comment]
@saytinh This isn't  forum for general support. This repository is for the build script for generating the base images used by Raspbian.

**Comment by saytinh** [comment]
@Landrash I know that but simply I can't find any where to support. I'd better to give up. Sad

**Comment by XECDesign** [comment]
https://www.raspberrypi.org/forums/
