### ISSUE TITLE
Raspbian: Name the second partition with a sane name

### ISSUE THREAD

**Issue by JamesH65** [RPi-Distro/pi-gen#131]
The boot partition is given a nice easy to use name, "boot", but the second partition uses the default name which is a long winded hex number related, I think to the SD card . I'd suggest naming it to something like "rootfs". 

Reason is that when writing scripts to copy stuff to the SD card, having a static and memorable name means that the scripts don't need to change between SD cards/systems.

**Comment by XECDesign** [comment]
Good call, thanks. Fixed.
