### ISSUE TITLE
pi-gen/export-image/prerun.sh

### ISSUE THREAD

**Issue by init76** [RPi-Distro/pi-gen#132]
Hi,

I got the following error when build.sh exports image on Ubuntu Ubuntu 17.10
"mkfs.ext4: invalid blocks '/dev/loop1' on device '^64bit,^metadata_csum,^huge_file"

I think there is an error in file pi-gen/export-image/prerun.sh at line 61 where a ' ' (space) is missing:
- is "..........-L rootfs-O $ROOT_FEA................"
- I think it should be "..............-L rootfs -O $ROOT_FEA................"

**Comment by XECDesign** [comment]
Thanks.
