### ISSUE TITLE
self referring symlink in /usr/bin/X11 

### ISSUE THREAD

**Issue by wan-tommy** [RPi-Distro/pi-gen#138]
In the raspbian image, directory /usr/bin/X11 has a symlink pointing to itself, that creates an infinite long of directory path like:
/usr/bin/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/.... 

(version is 2017-09-07-raspbian-stretch)

**Comment by XECDesign** [comment]
From `/usr/share/doc/x11-common/NEWS.Debian.g`:

> x11-common (1:7.0.11) unstable; urgency=low
> 
>    With the change to X11R7, various paths have been changed, including
>    where binaries are stored. In X11R6, binaries were installed to
>    /usr/X11R6/bin and /usr/bin/X11 was a symlink pointing to this
>    directory. Now binaries are installed to /usr/bin and /usr/bin/X11 is a
>    symlink that points to /usr/bin. As such, any legacy application that
>    installs its binaries to /usr/X11R6/bin may be outside your PATH, and
>    you will need to update the configuration on your system accordingly
