### ISSUE TITLE
How to modify .bashrc

### ISSUE THREAD

**Issue by didierbroska** [RPi-Distro/pi-gen#141]
Hello,

I would like add some lines in .bashrc file when to generate OS. I can see the 01-bashrc.diff, but I don't know how to make it.

Can you help me please ?

**Comment by XECDesign** [comment]
Would you like the changes to apply to a single user, all users or all newly created users? If you would like it to be a global change that applies to all users, you might be better of making a new file in /etc/profile.d/.

If you would only like to make the changes for a single existing user and would like to do it the way it's done in the example you give, then you'll need to become familiar with patches and quilt.

https://linux.die.net/man/1/quilt
http://www.shakthimaan.com/downloads/glv/quilt-tutorial/quilt-doc.pdf
https://stuff.mit.edu/afs/athena/system/i386_deb50/os/usr/share/doc/quilt/quilt.html

A file named 'EDIT' can be dropped into a patch substage to drop into bash during a build to edit/add/remove patches.
