### ISSUE TITLE
mount with discard?

### ISSUE THREAD

**Issue by jamesruan** [RPi-Distro/pi-gen#151]
We are considering using the box as a long running machine.
Is it good to add mount option `discard` for SD cards?

**Comment by XECDesign** [comment]
Hard to say.

From the manpage:

> This is useful for SSD devices and sparse/thinly-provisioned LUNs, but **it is off by default until sufficient testing has been done**.

Also:
https://askubuntu.com/a/195205
https://wiki.debian.org/SSDOptimization#WARNING
