### ISSUE TITLE
losing output on dockerized build

### ISSUE THREAD

**Issue by evandavey** [RPi-Distro/pi-gen#153]
When running ./build-docker.sh I get log output up until 

```
I: Unpacking the base system...
```

where the build appears to freeze.  However if I wait long enough and press enter, the build looks to have completed without further logs.

**Comment by XECDesign** [comment]
Does this happen only with docker builds?

**Comment by evandavey** [comment]
I believe so but I haven't been able to do a successful direct build yet (I am using Ubuntu for Windows 10).

**Comment by XECDesign** [comment]
And you're running docker from WLS as well? I'm surprised you've got that far.

**Comment by evandavey** [comment]
It's Docker for Windows and Hyper-V for the machines, then WSL also has the docker client installed and it connects via TCP.  Has been working fine on other projects, and seems odd that it continues until this point since by then it should be running within the virtual machine and not be impacted by WSL.

**Comment by evandavey** [comment]
Direct build keeps failing when downloading packages, and won't work with the dockerized APT proxy at all.

```
I: Validating xz-utils 5.2.2-1.2
I: Retrieving zlib1g 1:1.2.8.dfsg-5
I: Validating zlib1g 1:1.2.8.dfsg-5
E: Couldn't download packages: cron readline-common libp11-kit0
```

**Comment by XECDesign** [comment]
Any luck figuring this out? It doesn't sound a like a problem inherent to pi-gen.

**Comment by evandavey** [comment]
No.  I switched to building on a linux virtual machine as I needed to move on quickly for the project.

**Comment by XECDesign** [comment]
Alright, closing for now.
