### ISSUE TITLE
dependencies_check fail

### ISSUE THREAD

**Issue by ssfdre38** [RPi-Distro/pi-gen#17]
so i was testing the new build with sudo IMG_NAME="raspbian" ./build.sh and there is an error tossed from the dependencies_check file 
/home/ssfdre38/pi-gen/scripts/dependencies_check: line 27: unexpected EOF while looking for matching `"'
Line 27 is echo "$missing"

**Comment by hadmack** [comment]
I have the same problem, seems to be due to line 13 nested quotes for sed:

    deps="$(sed -f "${SCRIPT_DIR}/remove-comments.sed" < ${BASE_DIR}/depends"
  
but I don't know how to fix this.  It clearly must work on some system but not with my bash version.

**Comment by XECDesign** [comment]
Sorry, should've tested before merging that PR. Seems to just be a missing ')'.

**Comment by iKarith** [comment]
I must've accidentally deleted it just before committing, sorry.  :(

**Comment by XECDesign** [comment]
No worries, happens to everyone.

**Comment by iKarith** [comment]
(This got reopened by the comments, it should be re-closed.)

**Comment by XECDesign** [comment]
I was waiting for @ssfdre38 to close it or acknowledge that it's no longer an issue for him. Github didn't actually close this to begin with since the 'issue' in the commit message breaks that mechanism.
