### ISSUE TITLE
mount: can't find PARTUUID=ed8...

### ISSUE THREAD

**Issue by hagna** [RPi-Distro/pi-gen#175]
I'm on commit 93db373.  Made an image, but it won't boot.  Maybe the UUID is wrong?

mount: can't find PARTUUID=ed8...-01

**Comment by XECDesign** [comment]
What was the problem?

**Comment by hagna** [comment]
The image it produced was fine.  I modified /etc/fstab after the fact, and that caused the problem.

**Comment by XECDesign** [comment]
Ah alright, thanks.
