### ISSUE TITLE
NOOBS image does not build

### ISSUE THREAD

**Issue by dlabun** [RPi-Distro/pi-gen#180]
I am not sure what's changed recently, I am not getting a NOOBS image when running Pi-Gen. I've tried several times running the vanilla version straight off Github on a clean installation of Raspbian running in VMware and the image is never generated.

From looking at the build log, there's absolutely nothing that indicates the NOOBS image scripts were executed.

**Comment by dlabun** [comment]
Just to update... The deploy folder is never created in the process either. I do get my normal export image in the work folder.

**Comment by XECDesign** [comment]
Do you have appropriate stage*/EXPORT_NOOBS files? If so, could you please post their content your build.log (found in the work directory).

**Comment by dlabun** [comment]
Yes, I do have the EXPORT_NOOBS files. For the sake of troubleshooting I downloaded the most recent version of the repository and it won't even build completely. 

I've attached EXPORT_NOOBS from stage 5 (I changed the extension so Github would take it) and the complete build.log. Below is just the section relevant to the export process... That's not a copy / paste error, the log ends at begin 01-run.sh.

02:53:53] Begin /home/pi/Desktop/pi-gen-nov/export-image
[02:53:53] Begin /home/pi/Desktop/pi-gen-nov/export-image/prerun.sh
[02:54:26] End /home/pi/Desktop/pi-gen-nov/export-image/prerun.sh
[02:54:27] Begin /home/pi/Desktop/pi-gen-nov/export-image/00-allow-rerun
[02:54:27] Begin /home/pi/Desktop/pi-gen-nov/export-image/00-allow-rerun/00-run.sh
[02:54:27] End /home/pi/Desktop/pi-gen-nov/export-image/00-allow-rerun/00-run.sh
[02:54:27] End /home/pi/Desktop/pi-gen-nov/export-image/00-allow-rerun
[02:54:27] Begin /home/pi/Desktop/pi-gen-nov/export-image/01-set-sources
[02:54:27] Begin /home/pi/Desktop/pi-gen-nov/export-image/01-set-sources/00-patches
[02:54:27] End /home/pi/Desktop/pi-gen-nov/export-image/01-set-sources/00-patches
[02:54:27] Begin /home/pi/Desktop/pi-gen-nov/export-image/01-set-sources/01-run.sh
[02:54:42] End /home/pi/Desktop/pi-gen-nov/export-image/01-set-sources/01-run.sh
[02:54:42] End /home/pi/Desktop/pi-gen-nov/export-image/01-set-sources
[02:54:42] Begin /home/pi/Desktop/pi-gen-nov/export-image/02-network
[02:54:42] Begin /home/pi/Desktop/pi-gen-nov/export-image/02-network/01-run.sh
[02:54:42] End /home/pi/Desktop/pi-gen-nov/export-image/02-network/01-run.sh
[02:54:42] End /home/pi/Desktop/pi-gen-nov/export-image/02-network
[02:54:42] Begin /home/pi/Desktop/pi-gen-nov/export-image/03-set-partuuid
[02:54:42] Begin /home/pi/Desktop/pi-gen-nov/export-image/03-set-partuuid/00-run.sh
[02:54:42] End /home/pi/Desktop/pi-gen-nov/export-image/03-set-partuuid/00-run.sh
[02:54:42] End /home/pi/Desktop/pi-gen-nov/export-image/03-set-partuuid
[02:54:42] Begin /home/pi/Desktop/pi-gen-nov/export-image/04-finalise
[02:54:42] Begin /home/pi/Desktop/pi-gen-nov/export-image/04-finalise/01-run.sh


[build.log](https://github.com/RPi-Distro/pi-gen/files/1943603/build.log)

[EXPORT_NOOBS.txt](https://github.com/RPi-Distro/pi-gen/files/1943605/EXPORT_NOOBS.txt)

**Comment by dlabun** [comment]
No, both cloning and downloading releases are failing. At first I got I broke something in my clone, but even fresh clones are no good.

**Comment by XECDesign** [comment]
In export-image/04-finalise/01-run.sh, could you put 'set -x' near the start of the file, run the build and then paste the last chunk of output?

**Comment by kelsieflynn** [comment]
I dont know if this matters but I built three images forked off this project , then the last one I built began failing after a update to :https://archive.raspberrypi.org/debian/dists/stretch/
After this new sysnc, I had to chroot in and finish my last project afterwards because the image would not build after that for me.  This may have nothing to do with your issues or it may.  However, like I mentioned, this may not help with this problem. Regardless, I have not built a single image from pi-gen since archive.raspberrypi.org was updated, I have not tried in several days.  If it would help I can try a fresh git clone and attempt another rebuild to get the error message, if any still exists.

**Comment by dlabun** [comment]
Okay it just finished running and here's what I got:

````
+ ln -nsf /proc/mounts /home/pi/Desktop/pi-gen-nov/work/2018-04-24-RaspbianTest/export-image/rootfs/etc/mtab
++ find /home/pi/Desktop/pi-gen-nov/work/2018-04-24-RaspbianTest/export-image/rootfs/var/log/ -type f
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ for _FILE in $(find ${ROOTFS_DIR}/var/log/ -type f)
+ true
+ rm -f /home/pi/Desktop/pi-gen-nov/work/2018-04-24-RaspbianTest/export-image/rootfs/root/.vnc/private.key
+ rm -f /home/pi/Desktop/pi-gen-nov/work/2018-04-24-RaspbianTest/export-image/rootfs/etc/vnc/updateid
++ basename /home/pi/Desktop/pi-gen-nov/stage2
+ update_issue stage2
+ local GIT_HASH
++ git rev-parse HEAD
fatal: Not a git repository (or any of the parent directories): .git
+ GIT_HASH=
pi@raspberry:
````

**Comment by kelsieflynn** [comment]
@XECDesign  
While trying to build a lite image through stage two i've seen this a couple times.
START COPY:
Command (m for help): 
Disk /home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-image/2018-04-24-TestBuild20180424-4GB.img: 800 MiB, 838860800 bytes, 1638400 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x804ef162

Device                                                                                                                    Boot Start     End Sectors  Size Id Type
/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-image/2018-04-24-TestBuild20180424-4GB.img1       8192    8192       1  512B  c W95 FAT32 (LBA)
/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-image/2018-04-24-TestBuild20180424-4GB.img2      16384 1638399 1622016  792M 83 Linux

Command (m for help): The partition table has been altered.
Syncing disks.

/boot: offset 4194304, length 512
/:     offset 8388608, length 830472192
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkdosfs: Too few blocks for viable filesystem

END PASTE


Perhaps Im just nuts but, or perhaps im just nuts AND
My deduction, is the math is wrong on calculating the  boot partition as a 512 byte size is just large enough for a boot sector but nothing else really.

**Comment by kelsieflynn** [comment]
Here's  a better copy paste of whole event:
START COPY:

[16:07:56] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image/03-set-partuuid/00-run.sh
[16:07:56] End /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image/03-set-partuuid/00-run.sh
[16:07:56] End /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image/03-set-partuuid
[16:07:56] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image/04-finalise
[16:07:57] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image/04-finalise/01-run.sh
Stopping fake hwclock: saving system time.
Mode:     real
Files:    2289
Linked:   411 files
Compared: 0 xattrs
Compared: 633 files
Saved:    14.37 MiB
Duration: 0.32 seconds
14905/189452/427008
  adding: 2018-04-24-TestBuild20180424-lite.img (deflated 80%)
[16:10:26] End /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image/04-finalise/01-run.sh
[16:10:26] End /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image/04-finalise
[16:10:26] End /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image
[16:10:26] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-noobs
[16:10:26] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-noobs/prerun.sh
/boot: offset 4194304, length 45206016
/:     offset 50331648, length 1749024768
'/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-noobs/rootfs/etc/systemd/system/multi-user.target.wants/apply_noobs_os_config.service' -> '/lib/systemd/system/apply_noobs_os_config.service'
[16:22:17] End /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-noobs/prerun.sh
[16:22:17] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-noobs/00-release
[16:22:17] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-noobs/00-release/00-run.sh
'files/partition_setup.sh' -> '/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-noobs/2018-04-24-TestBuild20180424-lite/partition_setup.sh'
'files/partitions.json' -> '/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-noobs/2018-04-24-TestBuild20180424-lite/partitions.json'
'files/os.json' -> '/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-noobs/2018-04-24-TestBuild20180424-lite/os.json'
'files/OS.png' -> '/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-noobs/2018-04-24-TestBuild20180424-lite/OS.png'
'files/release_notes.txt' -> '/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-noobs/2018-04-24-TestBuild20180424-lite/release_notes.txt'
./
./slides_vga/
./slides_vga/G.png
./slides_vga/B.png
./slides_vga/E.png
./slides_vga/D.png
./slides_vga/A.png
./slides_vga/F.png
./slides_vga/C.png
[16:22:18] End /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-noobs/00-release/00-run.sh
[16:22:18] End /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-noobs/00-release
[16:22:18] End /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-noobs
[16:22:18] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image
[16:22:18] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image/prerun.sh
du: cannot access '/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/stage4/rootfs/boot': No such file or directory
du: cannot access '/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/stage4/rootfs': No such file or directory

Welcome to fdisk (util-linux 2.29.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x51c014e9.

Command (m for help): Created a new DOS disklabel with disk identifier 0x804ef162.

Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): 
Using default response p.
Partition number (1-4, default 1): First sector (2048-1638399, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (8192-1638399, default 1638399): 
Created a new partition 1 of type 'Linux' and of size 512 B.

Command (m for help): Disk /home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-image/2018-04-24-TestBuild20180424-4GB.img: 800 MiB, 838860800 bytes, 1638400 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x804ef162

Device                                                                                                                    Boot Start   End Sectors  Size Id Type
/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-image/2018-04-24-TestBuild20180424-4GB.img1       8192  8192       1  512B 83 Linux

Command (m for help): Selected partition 1
Partition type (type L to list all types): Changed type of partition 'Linux' to 'W95 FAT32 (LBA)'.

Command (m for help): Partition type
   p   primary (1 primary, 0 extended, 3 free)
   e   extended (container for logical partitions)
Select (default p): 
Using default response p.
Partition number (2-4, default 2): First sector (2048-1638399, default 2048): Last sector, +sectors or +size{K,M,G,T,P} (16384-1638399, default 1638399): 
Created a new partition 2 of type 'Linux' and of size 792 MiB.

Command (m for help): 

Command (m for help): 
Disk /home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-image/2018-04-24-TestBuild20180424-4GB.img: 800 MiB, 838860800 bytes, 1638400 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x804ef162

Device                                                                                                                    Boot Start     End Sectors  Size Id Type
/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-image/2018-04-24-TestBuild20180424-4GB.img1       8192    8192       1  512B  c W95 FAT32 (LBA)
/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/export-image/2018-04-24-TestBuild20180424-4GB.img2      16384 1638399 1622016  792M 83 Linux

Command (m for help): The partition table has been altered.
Syncing disks.

/boot: offset 4194304, length 512
/:     offset 8388608, length 830472192
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
mkdosfs: Too few blocks for viable filesystem


END PASTE

**Comment by kelsieflynn** [comment]
Also note, I personally have no issue as I can work around the n00bs issue and build as "lite" for my needs mostly, I'm just trying to help on what I noticed before about a 512byte part that seemed strange during a noobs generation.

**Comment by dlabun** [comment]
@kelsieflynn I take it you made that clone today? What's your build environment?

I'm going to spin up a fresh VM just to see if I do fail in the same spot or if I can make it as far as you.

**Comment by kelsieflynn** [comment]
@dlabun 

Qemu virt running debian 9update4

All I did was fresh clone it today and then add a config name, added SKIP files to stages 3,4,5
then ran build.sh

**Comment by dlabun** [comment]
I have a fresh clone running in a new Raspbian VM, let's see how this goes... It looks like the mirrors are a little slow today so it's taking a while.

(FYI, not a Linux developer at all... I'm hardware only)

**Comment by kelsieflynn** [comment]
I think I see more about what failed  on my setup and why it only got a 512K boot part when trying to create the last image.

"[16:22:18] Begin /home/dev1/NEWCLONE_4.24.2018/pi-gen/export-image/prerun.sh
du: cannot access '/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/stage4/rootfs/boot': No such file or directory
du: cannot access '/home/dev1/NEWCLONE_4.24.2018/pi-gen/work/2018-04-24-TestBuild20180424/stage4/rootfs': No such file or directory"



It appears to me that in the code below is where the BOOT size is set and since for some reason
it can not re-open the  chroot any longer it defaulted to a boot partition with 8192/8192 or 512 bytes in length.

From :
https://github.com/RPi-Distro/pi-gen/blob/master/export-image/prerun.sh

BOOT_SIZE=$(du --apparent-size -s "${EXPORT_ROOTFS_DIR}/boot" --block-size=1 | cut -f 1)


It makes sence to me why mine failed as why du complained first and why because without my old
chroot mount, no APPARENT-SIZE exists, which the BOOT_SIZE var depends on.

Real question might be now, why did my boot chroot close after it created the "lite" stage and if it did close, why cant the noobs stage reopen?

**Comment by XECDesign** [comment]
@dlabun that really looks like you're not running it from a git cloned directory.

The failing line is `git rev-parse HEAD`, which isn't anything fancy.

What does `ls -la /home/pi/Desktop/pi-gen-nov/.git/` say?

**Comment by dlabun** [comment]
I started from scratch last night and everything is working correctly now... The only thing I could figure is that the something on my system became corrupt and was causing the script to think it wasn't a git clone directory. 

Is running the tool on Raspbian advisable or should I be doing it elsewhere?

**Comment by XECDesign** [comment]
I haven't used it under Raspbian since writing the initial version, so I don't know if it still works. Current stable releases of Debian and Ubuntu should work.

**Comment by kelsieflynn** [comment]
Im still curious about what happens when I build it as lite. I'll rebuild mine fresh again today without the SKIP files and see if it creates the noobs portion in my setup, perhaps thats how its suppose to work in a lite build, duh.  I have both debian 9u4 and ubuntu LTS(latest) setup, I'll try both. Eitherway, as mentioned before, I dont really have a problem with the script myself as I'm not using the noobs portion but I would still like to understand what I'm missing in my understanding here.

**Comment by XECDesign** [comment]
@kelsieflynn I've tried to skim through your posts for relevant information, but I'm struggling to understand what the problem is.

You said you added SKIP files for stages 3, 4 & 5, and then your lite images build fine? Yet, it looks like you're still trying to export later stages (which of course wouldn't work if you haven't built them). Have you deleted the EXPORT* files from those later stages?

A short summary with the relevant error messages would be helpful.

**Comment by kelsieflynn** [comment]
@XECDesign    
I dont have a problem per say.  I've experimented a lot with this great setup, and I managed to get a few builds that worked for my cases. When something has gone wrong, I'm sure I triggered something out of order or didnt understand what was happening in the stages fully.
 I've re-read over the instructions, seems like I missed putting  a SKIP_IMAGES or something before.  Everything works as intended, when i follow the script exactly.   

What appeared to be a problem may have been my curiosity going wild,  as to how the script works when creating the noobs portion.  All's good here though, script works great.  I dont have to tell you this script is great as you all can tell from the # of forks. But anyway, its great, all I need now is my local mirrors of the repos setup or at least a deb squid cache.

**Comment by kelsieflynn** [comment]
Sorry for  the noise, Everyone struggles following me, mostly because i have a little bit of ADHD, talk to myself often, answer back often, and I go on long curiosity tangents. Its all part of my how I roll.

**Comment by XECDesign** [comment]
@dlabun okay to close?

**Comment by dlabun** [comment]
Absolutely, thanks for the help!

**Comment by geromueller** [comment]
Hi all! I just came across the same problem. After the update (from Febr.) my setup is not working anymore.

**Comment by kevinastone** [comment]
I ran into this issue today.  I have `pi-gen` checked out as a git submodule in my larger project repo and build the images using docker.  Since docker cannot access the parent repo, this command here fails: https://github.com/RPi-Distro/pi-gen/blob/master/scripts/common#L98

Would the team be interested to move setting and passing on `GIT_HASH` to the `build.sh` and `build-docker.sh` scripts?  I'd think this is less fragile than trying to access the git repo in the build process itself.

**Comment by XECDesign** [comment]
> passing on `GIT_HASH` to the `build.sh`

Passing from where?

**Comment by kevinastone** [comment]
Something like this where `build.sh` and `build-docker.sh` determine the git-hash and pass it into the build stages.

This would also allow overriding this in the build config file.

https://github.com/kevinastone/pi-gen/commit/a171ecff415436e4e36f1ad482e308877ab2804b

**Comment by XECDesign** [comment]
Ah, passing FROM build.sh rather than to build.sh? Yeah, if it solves the problem, why not.
