### ISSUE TITLE
4 GB image: unable to install Mathematica later

### ISSUE THREAD

**Issue by maxnet** [RPi-Distro/pi-gen#202]
If using the 4 GB image, one is unable to install Mathematica later using your "recommended software" app.

![2018-07-29-162947_1920x1080_scrot](https://user-images.githubusercontent.com/1123701/43368521-9c2ddf7a-935e-11e8-922a-c160763c06df.png)

Probably because it is missing the debconf preseed value that auto-acccepts the license agreement in that case, and the "recommended software" app not supporting interactive prompts.
Perhaps also add the debconf value a stage earlier?

**Comment by XECDesign** [comment]
Thanks, Floris.

@spl237, would you like to fix this in recommended software or just accept the license by default on all images? I wonder if the other software installer in the menu also has the same problem.

**Comment by spl237** [comment]
I can't think of any circumstances under which someone would want to install the software and then refuse the license. Accepting the license by default is probably the easiest option - is there an easy way of doing that?

**Comment by spl237** [comment]
Yes - https://www.freedesktop.org/software/PackageKit/pk-faq.html#user-interaction - you can't ask the user to accept a license under a PackageKit install.

**Comment by XECDesign** [comment]
Yes, as Floris says, we can 'accept' the license earlier on.

One way for the installer to handle this case would be to let the user know of the license and run the appropriate debconf command to accept the license, but that may be unnecessary complexity.

We have the license information on the download page of the images, so I suppose there's no problem with just going with the first option and not touching prefapps.

**Comment by maxnet** [comment]
BTW there are also some other issues when installing/uninstalling Mathematica and Bigfoot.

![menu-items-not-removed](https://user-images.githubusercontent.com/1123701/43371081-ff8fb7d8-938a-11e8-8f8e-67078de56e4a.png)

Menu items are not instantly removed after uninstall, but require logoff/login again.
And once in a while (not always) they do not appear instantly after installation either. Making it look to the average end-user like installation failed...

When installing/uninstalling other packages (e.g. Geany) it does always seem to add/remove menu item  properly.
Like it is only those two packages that are doing something non-standard that does not cause the trigger that updates menus to be invoked.
No idea if it's a problem in the .deb package, the rasp-ui-override stuff, the installer, LXDE or elsewhere.
But perhaps something you can find a workaround for (e.g. always force lxpanel to refresh whole menu after any install/uninstall or whatever).

**Comment by spl237** [comment]
It may be related to the fact that those apps have override .desktop files (although some others do as well, such as bluej). I've noticed occasional problems of the type you describe, but have never been able to reliably repeat them. My gut feel is that it is an LXDE issue rather than anything application-specific; I'll see if I can find anything.

**Comment by maxnet** [comment]
Ignore my last post. bluej has same postrm script as greenfoot, and does uninstall properly.


Wonder if it's perhaps specific to timing or the order in which files are removed.
E.g. the removal of the .deskop file in /usr/share/applications triggering immediate regenerating of the entire menu.
But the .deskop file in rpi-override is never removed.
If the application executable it refers to hasn't been deleted yet and is still there by the time it processes the override .desktop file, the menu item stays.
If application executable has already been removed by the time it process the .desktop file, menu item does is removed properly.

Anyway. Perhaps simplest workaround is to simply call `lxpanelctl refresh` after any package installation/removal is fully complete.

**Comment by XECDesign** [comment]
Closing since we no longer distribute mathematica.
