### ISSUE TITLE
Install software by "git clone" for Lite image

### ISSUE THREAD

**Issue by hongquan** [RPi-Distro/pi-gen#210]
I want to make a custom image based on Lite Raspbian (no GUI), to pre-include [our software](https://github.com/fossasia/susi_linux/).
The installation process is to clone the git repo and run the _install.sh_ script inside.

1. Should I modify stage2 or create stage2.5?
2. Which script should I modify to add that step (mkdir > cd > git clone > ./install.sh).

**Comment by XECDesign** [comment]
There's no prescriptive way to use pi-gen. The Raspbian build files are provided as an example for how we do everything.

**Comment by hongquan** [comment]
Ok. I'm trying creating subtage _stage2/03-susi_. Let see if it works.

**Comment by AlvaroCs2020** [comment]
@hongquan Hi! How are you doing? maybe it just a too old post, but do you remember how do you solve this?

**Comment by hongquan** [comment]
@AlvaroCs2020 We created "stage2.5". You can read more here:

http://talk.quan.hoabinh.vn/customize-linux-embedded/
