### ISSUE TITLE
2018-10-09 issues

### ISSUE THREAD

**Issue by XECDesign** [RPi-Distro/pi-gen#211]
Mostly a note to self.

Fix before next release:
* ~~Timezone wasn't set properly~~ (33e94c46f32fb2e9b1f7106d7a790f074815dfd1)
* ~~/debootstrap directory was left over~~ (7ccf8185b39062afe399f2bdd2b327f5f4460327)

**Comment by XECDesign** [comment]
Yup, it occured to me that would be an issue after I pushed https://github.com/RPi-Distro/pi-gen/commit/7ccf8185b39062afe399f2bdd2b327f5f4460327 . Instead, it should only run that rmdir command if the directory exists. Will get it fixed on Monday.

**Comment by jcwren** [comment]
Any reason not to 'rm -f' it instead?

--jc

Save a life; adopt a shelter animal.

**Comment by XECDesign** [comment]
It should delete the directory if it exists and fail if it's not empty.

`rm -f` will error out saying it's a directory. `rm -rf` will return 0 whether or not the directory exists and whether or not it's empty.

It's a workaround for a bug. Normally, when you delete a file, the applications which have it open keep a reference to it and the filesystem removes it properly when those applications close. Some filesystems, like those provided through FUSE keep a hidden file instead.

The last thing debootstrap does is move the log file and delete the folder. On those filesystems, this fails because the directory cannot be emptied and debootstrap fails (because it still has the log file open after it moves it).

I used ` || rdmir` to say "If debootstrap fails, but the directory is empty, continue anyway, because it was probably fine". For some reason (a newer version of debootstrap, perhaps), the debootstrap directory was left behind in the last build. Indicating that it finished without any errors, but kept the directory, so rmdir never ran.

**Comment by XECDesign** [comment]
Should be fixed now
