### ISSUE TITLE
if the wifi regulatory domain is not going to default to `uk`, then the keyboard layout and locale should not be changed from distro defaults either.

### ISSUE THREAD

**Issue by sneak** [RPi-Distro/pi-gen#212]
Simple consistency.  Either the system should be fully localised (teehee) for en_GB including wifi regulatory domain, or it should not.

I get that it's impossible to estimate where the system will be used and the rationale for not changing it lest RF law be broken; but by the exact same token it is impossible to estimate what type of keyboard will be connected and thus the keyboard layout and locale should not be changed from distro defaults.

https://github.com/RPi-Distro/pi-gen/blob/33e94c46f32fb2e9b1f7106d7a790f074815dfd1/stage2/01-sys-tweaks/00-debconf#L18

**Comment by XECDesign** [comment]
It's a UK product. Shipped with UK defaults where it's safe to do so.

**Comment by sneak** [comment]
A UK product—with chips made in China, based on an OS distribution built on the internet with contributors from every industrialized nation in the world, with a kernel originally written by a Finn, whose largest base of users is in the US.  Any which way you slice it, from supply chain, to work-hours input, to the needs of your primary user base—your national defaults are wrong.

I am willing to bet the #1 single most occurring troubleshooting issue that new users have is that their keyboard doesn't work right because you changed the distro away from its defaults, catering to a small minority of your userbase in some misguided nationalistic urge.

Sort of makes the "but users will have trouble and blame Raspbian!" rationale of #207 sound silly, doesn't it?

**Comment by jcwren** [comment]
I know the keyboard thing bites me just about every time. U-S-A! U-S-A! U-S-A!

I did include running a shell script in my set that goes in and "fixes" things to USA, but it sure wouldn't hurt my feelings if en_US was the default.

**Comment by XECDesign** [comment]
Trying to get personal doesn't accomplish anything. I'm not from the UK and my input on these decisions is fairly minor. This isn't a personal project, it's an internal tool that was released because people asked for it. If somebody finds it useful, fantastic. If they want to do their own thing, also great.

**Comment by sneak** [comment]
I don't think the default should be changed; I think it should be left to the upstream distro default.  pi-gen explicitly changes it from whatever the upstream distro default is to uk/en_GB.  I don't advocate selecting any one country's layout over any other, but simply defaulting to unset.

**Comment by sneak** [comment]
@jcwren #207 makes it so that you could include a shell script on /boot and stop maintaining your own fork, but it was rejected as being "too dangerous to the brand because newbies would misuse it".

**Comment by jcwren** [comment]
I know this issue was closed, but it occurred to me, could the build process look at the locale of the docker container and use that to select the WiFi region, keyboard layout, etc?

**Comment by XECDesign** [comment]
Sounds like a good idea. I'd accept that as long as it's something that has to be enabled rather than default behavior. I have systems with different combinations of localisation settings, so it would be asking for trouble.

**Comment by jcwren** [comment]
I'm not smart enough about docker to know how do it. Maybe someone else is and can come up with something :)
