### ISSUE TITLE
Failures inside on_chroot do not stop the build

### ISSUE THREAD

**Issue by tomas-c** [RPi-Distro/pi-gen#217]
Most build scripts have "-e" option which is meant to make failed commands interrupt the script.

However, if any commands fail inside `on_chroot` call, the build still continues.

This seems a bit risky as you can only notice failures by carefully analysing build logs.

Replacing all instances of `on_chroot` with `on_chroot -e` fixes this.

**Comment by XECDesign** [comment]
Good idea. Does only changing https://github.com/RPi-Distro/pi-gen/blob/master/scripts/common#L91 to `capsh --drop=cap_setfcap "--chroot=${ROOTFS_DIR}/" -- "-e $@"` do the job?

**Comment by tomas-c** [comment]
It works if I move -e outside the quotes. I have created #219 with the necessary code changes.
