### ISSUE TITLE
`realpath` is not a package in apt.

### ISSUE THREAD

**Issue by gravypod** [RPi-Distro/pi-gen#230]
I was following the setup guide in the `README.md` and when I ran 

```
apt-get install quilt parted realpath qemu-user-static debootstrap zerofree pxz zip \
dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl
```

apt printed out

```
Package realpath is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
```

I then ran `apt-cache search realpath` and it only found two things:

```
 ~ apt-cache search realpath
coreutils - GNU core utilities
node-fs.realpath - Use node's fs.realpath
```

Are you attempting to install the `coreutils` version of the command `realpath`?

Extra info:

OS Version: Ubuntu 18.10 cosmic

**Comment by andig** [comment]
Imho the same will be happening when upgrading to debian buster.

**Comment by XECDesign** [comment]
Should already be fixed by https://github.com/RPi-Distro/pi-gen/commit/21aeca1b0c1ffd4c3336be31da510315714e87a8 ?

**Comment by andig** [comment]
Its still in the Dockerfile:

    RUN apt-get -y update && \
        apt-get -y install \
            git vim parted \
            quilt realpath qemu-user-static debootstrap zerofree pxz zip dosfstools \
            bsdtar libcap2-bin rsync grep udev xz-utils curl xxd file kmod\
        && rm -rf /var/lib/apt/lists/*

**Comment by XECDesign** [comment]
Ah, thanks. Should be fine now?

**Comment by andig** [comment]
LGTM

**Comment by XECDesign** [comment]
Thanks
