### ISSUE TITLE
Wolfram debconf separated from package

### ISSUE THREAD

**Issue by infinnovation-dev** [RPi-Distro/pi-gen#234]
The debconf setting relating to the Wolfram EULA is applied in stage2, but wolfram-engine is not installed until stage5.  I don't think it breaks anything; it just seems an anomaly.

**Comment by XECDesign** [comment]
This was done to allow wolfram-engine to be installed from a lite image without being prompted to accept the EULA. The recommended software application doesn't support interactive installs. There should be an old issue here that resulted in the change.
