### ISSUE TITLE
Raspberry Pi Debian release key is unchecked.

### ISSUE THREAD

**Issue by jonesinator** [RPi-Distro/pi-gen#26]
In the bootstrap function in scripts/common the --no-check-gpg flag is provided to deboostrap. Seems like it would be a little better to embed the key signature somewhere in the repository, get the key, check it against the signature, and then if it is good add it to a keyring so that deboostrap can validate that the repository is authentic.

**Comment by paulfurley** [comment]
> Seems like it would be a little better to embed the key signature somewhere in the repository, get the key

:+1:

Or even just check the public key into this repository :)

**Comment by XECDesign** [comment]
Fixed by 8e377c407fff9469df598b8013ea36b81b1242bb
