### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by gudata** [RPi-Distro/pi-gen#263]
Is there a way to specify older kernel version?
When I removed the work/ folder the setup automagically starts pulling the new kernel 4.14.98+ instead of the previously one.

**Comment by XECDesign** [comment]
Not easily. You'd need to take the install of raspberrypi-kernel out of here https://github.com/RPi-Distro/pi-gen/blob/34780633cc971dcd237b6bb43a6220c8e5eb9eab/stage0/02-firmware/01-packages and install it some other way.

You can download the appropriate .deb from here http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/ and then install it using dpkg with on_chroot in a run.sh file. If that didn't make sense, you may have to look around pi-gen and figure out how it works.

**Comment by gudata** [comment]
Thanks!
