### ISSUE TITLE
set apt for DEBIAN_FRONTEND=noninteractive

### ISSUE THREAD

**Issue by FredericGuilbault** [RPi-Distro/pi-gen#269]
When there is multiple users created, Wicd package prompt a ncurse dialog.

![wicd](https://user-images.githubusercontent.com/37122999/54458070-6d103f00-4739-11e9-983c-0501458c5d34.png)

 
So I have to move the install process to a run.sh file and go like this: 
```
on_chroot << EOF
export DEBIAN_FRONTEND=noninteractive
apt install -y wicd wicd-curses wicd-gtk
EOF
```

I can't figure a use case wher pi-gen would need user-interaction during the compiling. Maybe it would be a good improvement to set the `export DEBIAN_FRONTEND=noninteractive` variable by default.

**Comment by XECDesign** [comment]
The idea was that the build should interrupt so that I can go back and preseed whatever new debconf options come up. Otherwise packages could make assumptions and I wouldn't know what they are.

**Comment by FredericGuilbault** [comment]
good point.
