### ISSUE TITLE
Feature Request: Change locales

### ISSUE THREAD

**Issue by walchko** [RPi-Distro/pi-gen#277]
The default is `en_GB.UTF-8`. Could you add something to the config file (`sudo build.sh -c config`)  to change the default to another language?

**Comment by XECDesign** [comment]
That's a little trickier than the rest of the options because it's currently set using a static file - https://github.com/RPi-Distro/pi-gen/blob/master/stage0/01-locale/00-debconf

**Comment by 132ikl** [comment]
Unless I am misunderstanding, aren't all the other config options set by just replacing a value in a static file to a variable? I don't see what the issue here is.
