### ISSUE TITLE
Is STAGE_LIST option working right?

### ISSUE THREAD

**Issue by sailoog** [RPi-Distro/pi-gen#288]
I want to skip stage5 without using SKIP files or editing it, so I add this to config:

STAGE_LIST=stage0 stage1 stage2 stage3 stage4 stage6 stage7 stage8

but it does not work. Am I misunderstanding anything?

**Comment by samtygier** [comment]
You probably need quotes.

`STAGE_LIST="stage0 stage1 stage2 stage3 stage4 stage6 stage7 stage8"`

**Comment by sailoog** [comment]
ops, it works, thanks!
