### ISSUE TITLE
Missing tag for latest Raspbian release

### ISSUE THREAD

**Issue by acinonyx** [RPi-Distro/pi-gen#324]
The latest Raspbian Buster image in [raspberrypi.org](https://www.raspberrypi.org/downloads/raspbian/) has a release date of  2019-07-10. Nevertheless, there is no such tag in `pi-gen` repository. The latest tag is `2019-06-20-raspbian-buster`. Thus, there is no way to be sure which commit was used to create the image.

**Comment by acinonyx** [comment]
Based on the contents of `release_notes.txt`, it seems that 175dfb027ffabd4b8d5080097af0e51ed9a4a56c is the commit which was used to generate the image.

**Comment by XECDesign** [comment]
Thanks. Tagged.
