### ISSUE TITLE
Real-time kernel builds?

### ISSUE THREAD

**Issue by JonnyTech** [RPi-Distro/pi-gen#327]
Is it possible to create images containing a real-time kernel?

**Comment by XECDesign** [comment]
I don't see why not.

**Comment by JonnyTech** [comment]
Excellent! Which settings need to be applied? I cannot find anything within the documentation.

**Comment by XECDesign** [comment]
There's nothing specific, you'll need to be general familiarity with pi-gen and what you want to do exactly. The existing stages have plenty of example showing how to copy files, execute scripts, add repos, install packages and so on. There's no "install custom kernel" setting or anything like that.

**Comment by artynet** [comment]
@JonnyTech check out this repo :

https://github.com/hypriot/rpi-kernel

I use customised version of these scripts to build my own kernel DEBS, they're quite simple to tweak....

**Comment by JonnyTech** [comment]
Thanks all
