### ISSUE TITLE
Error when executing build.sh

### ISSUE THREAD

**Issue by hj91** [RPi-Distro/pi-gen#33]
I am constantly getting IMG_NAME not set and can't get build process to start. 

What can be the possible cause for this error? I even checked local env settings. 

Code is cloned directly from github.

**Comment by XECDesign** [comment]
`echo IMG_NAME=raspbian-jessie >> config`

**Comment by hj91** [comment]
Can I replace raspbian-jessie by some other name?

**Comment by XECDesign** [comment]
yup

**Comment by hj91** [comment]
Thank you. I will check it.
