### ISSUE TITLE
Build failed at stage 4

### ISSUE THREAD

**Issue by hj91** [RPi-Distro/pi-gen#34]
ownership of `/home/harshad/pi-gen-dev/work/2016-12-04-harry/stage4/rootfs/home/pi/python_games' retained as harshad:harshad

rsync: - - chown=1000:1000: unknown option
rsync error:syntax or usage error (code 1) at main.c(1453) [client=3.0.9]

What has gone wrong here?

**Comment by XECDesign** [comment]
What's the host distro (and version) you're using?

**Comment by hj91** [comment]
It is 64 bit Ubuntu 14.10 and x86 platform.

**Comment by XECDesign** [comment]
What does 'rsync --version' report?

**Comment by hj91** [comment]
It's 3.0.9

--sent from mobile device--

**Comment by XECDesign** [comment]
I'm on 3.1.0:

>     - Added the --usermap/--groupmap/--chown options for manipulating file
>      ownership during the copy.
https://download.samba.org/pub/rsync/src/rsync-3.1.0-NEWS

**Comment by hj91** [comment]
OK, I will try it.

--sent from mobile device--

**Comment by hj91** [comment]
Updated rsync to latest version and managed to build default raspbian lite and raspbian full image. 

Now to customize its artwork and other related packages that are bundled by default. 

Is it possible to modify those images they show during installation!? For eg - I do not want to pack wolfram in my image. 

Please suggest a workaround for changing logo and icons. Want to include opensource and free stuff only.

**Comment by XECDesign** [comment]
To remove a package, just remove it from the stage's package list. If you'd like to modify a package, you're mostly on your own there. I would put custom packages into a separate repo and override the ones in raspberrypi.org.

You can use the icons under the BSD 3-clause license.

**Comment by hj91** [comment]
Thank you.
