### ISSUE TITLE
Shrink the size of the image file

### ISSUE THREAD

**Issue by bamb00dark** [RPi-Distro/pi-gen#36]
The size of the final image files seems to be determined in "export-image/prerun.sh" script file with the following command.
`IMG_SIZE=$(expr $BOOT_SIZE \* 2 \+ $TOTAL_SIZE \+ 512)M`

I understand the boot size and total size part in this command, but I'm not sure why an extra 512M space is needed.

For now, I'm trying to create a image file with size as small as possible. I know that a lite version image is created in stage2, however, its size still over 1GB. How can I shrink the size more?

**Comment by XECDesign** [comment]
512MB is wiggle room, so feel free to reduce it if you don't need it. A 100MB swap file is created on first boot. I haven't actually checked how much space is really required to safely boot for the first time.
