### ISSUE TITLE
WPA_PASSWORD unset

### ISSUE THREAD

**Issue by kraeml** [RPi-Distro/pi-gen#368]
I run into an error "WPA_PASSWORD" must be between 8 and 63 characters.

I don't want a WPA_PASSWORD because I use my wifi setup by own scripts.

Workaround is to set WPA_PASSWORD=dummy_password AND no WPA_ESSID. No errors but not so elegant. If no WPA_PASSWORD is set then no length test is required.

May look at:

https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash

**Comment by samtygier** [comment]
My bad sorry, I didn't check the case of WPA_PASSWORD being unset in #366 . I'll prep a new patch.
