### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by uSpike** [RPi-Distro/pi-gen#38]
`rsync` and `realpath` are missing as dependencies in `depends`.  I am trying to build inside a docker container pulled from `ubuntu:trusty`.

In addition, would the maintainers be interested in a PR for a docker-ized build system?  It would be an addition in the form of a `Makefile` and `Dockerfile` only.

**Comment by XECDesign** [comment]
Thanks, I'll add the depends next time. If it's easily maintainable and doesn't interfere with the 'normal' usage, I am sure that would be very useful.

**Comment by cfstras** [comment]
@uSpike: looks like I did not find your issue a week ago -- see #40 for my attempt at the docker-ization :) Would love any comments on it.
