### ISSUE TITLE
What does ##-run-chroot.sh do?

### ISSUE THREAD

**Issue by Taikuh** [RPi-Distro/pi-gen#392]
I'm having a hard time understanding what run-chroot.sh does.  
Am I correct in saying that build.sh creates a sort of mounted file system within the work directory for every stage?  
So, run-chroot.sh executes as this micro-mounted file system's root user, using its stage's $FSROOT as the CWD?
Whereas, run.sh just executes as myself in my normal file system, as per usual?

**Comment by XECDesign** [comment]
That sounds about right, yes.
