### ISSUE TITLE
Raspberry Pi Imager should be included in Raspberry Pi OS w/desktop

### ISSUE THREAD

**Issue by andrum99** [RPi-Distro/pi-gen#409]
Raspberry Pi Imager should be included in Raspberry Pi OS with desktop by default. The package name is 'rpi-imager'.

**Comment by spl237** [comment]
I think this would just cause confusion; the purpose of the imager is to create cards for the Pi. If it ran on the Pi itself, I can guarantee that people would complain about not being able to flash an image to the card they'd booted from...

I think it's fine to have it in the apt repo in case people want it, but it shouldn't be preinstalled; most people won't want to create cards on a Pi.
