### ISSUE TITLE
Build fails at stage2/01-sys-tweaks/03-console-setup.diff

### ISSUE THREAD

**Issue by tk721** [RPi-Distro/pi-gen#41]
My build on Ubuntu 14.04.4 LTS is failing with the following error:

```
Applying patch 03-console-setup.diff
patching file rootfs/etc/default/console-setup
Hunk #1 FAILED at 6.
1 out of 1 hunk FAILED -- rejects in file rootfs/etc/default/console-setup
Patch 03-console-setup.diff does not apply (enforce with -f)
```

It seems like the patch is expecting the following:

```
-CODESET="Lat15"
-FONTFACE="Fixed"
-FONTSIZE="8x16"
```

but the file to patch actually contains:

```
CODESET="guess"
FONTFACE="Fixed"
FONTSIZE="8x16"
```

As a part of the build process there was a graphical chooser for the codeset where the default was "guess", so I chose that. Manually editing `work/rootfs/etc/default/console-setup` fixes the issue and lets the build continue.

**Comment by XECDesign** [comment]
Will be fixed when PR #40 goes through.
