### ISSUE TITLE
Is this the 64-bit raspios pi-gen repository?

### ISSUE THREAD

**Issue by davesteele** [RPi-Distro/pi-gen#413]
Will this repository eventually contain the changes used to support generating the 64-bit images for Raspberry Pi OS? If not, does anyone know where the image generator is homed?

I'm confused, because the 32 bit images, which have been renamed, appear to still be part of this chain, but there's no sign of 64-bit support here.

**Comment by XECDesign** [comment]
Yes, I'll add an arm64 branch.

**Comment by davesteele** [comment]
Thanks. Build tags for the 5/27 build would also be appreciated.

**Comment by carl1stcallhelpcouk** [comment]
> Yes, I'll add an arm64 branch.

Any idea when?

**Comment by luigifreitas** [comment]
@XECDesign I think this issue could be closed since the `arm64` is now available.

**Comment by fuji246** [comment]
Is the arm64 branch ready to use?

**Comment by lurch** [comment]
Depends what you mean by "ready", but AFAIK the arm64 branch is what's used to create http://downloads.raspberrypi.org/raspios_arm64/images/ (which is still in beta - see https://github.com/raspberrypi/Raspberry-Pi-OS-64bit )
