### ISSUE TITLE
Way to specify which stage to run to?

### ISSUE THREAD

**Issue by sam3d** [RPi-Distro/pi-gen#42]
Had a brief look over `build.sh` and was wondering if there was a good way to execute the build script up to a certain stage (stage 2, to get just the _lite_ system, for example).

**Comment by XECDesign** [comment]
not pretty, but `touch stage3/SKIP stage4/SKIP`

**Comment by XECDesign** [comment]
and rm `stage4/EXPORT*`

**Comment by sam3d** [comment]
Wow that was quick, thank you! Good to know there is a way (however non-pretty it may be). Mind if I open a PR to document that in the README?

**Comment by XECDesign** [comment]
Go for it
