### ISSUE TITLE
64bit lite beta version?

### ISSUE THREAD

**Issue by guysoft** [RPi-Distro/pi-gen#429]
Hey,
So there is a 64bit beta version, but no 64bit lite beta version
(expected it to be in the url: https://downloads.raspberrypi.org/raspios_lite_arm64/images/)

We need it to builds, [OctoPi 64bit beta](https://community.octoprint.org/t/is-it-really-true-that-octoprint-does-not-support-4gb-version-of-pi4/21852/16), FullpageOS 64bit beta, [ZynthianOS 64bit beta](https://github.com/zynthian/zynthian-sys/issues/169), MagicMirror OS 64bit beta and so on.
Linked to related opened issues, will update as they grow.

In a way, this would let us give more feedback because nightlies from those communities are tested a lot more on small niche stuff over the full blown desktop 64bit, specifically for performance issues.

More detail:
The url for the lite images is:
https://downloads.raspberrypi.org/raspios_lite_armhf/images/

And the arm64 image is at:
https://downloads.raspberrypi.org/raspios_arm64/images/

But there is no url at:
https://downloads.raspberrypi.org/raspios_lite_arm64/images/

**Comment by lurch** [comment]
https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/9#issuecomment-679946520
