### ISSUE TITLE
Controller or keyboard not detected

### ISSUE THREAD

**Issue by maferland269** [RPi-Distro/pi-gen#44]
hey just downloaded and installed the image, 

it boots and i end up on the meny, but none of my remote (SNES or PS3) are detected, and, also, my keyboad...does not seem to be detected...any way to help me out?

**Comment by Landrash** [comment]
This is a repo for the script that generates the Raspbian image. I think your inte wrong github if your looking for support for gamepads.

**Comment by XECDesign** [comment]
I would recommend asking on the raspberry pi forum.
