### ISSUE TITLE
Latest pi-gen 64-bit build commit is not pushed

### ISSUE THREAD

**Issue by davesteele** [RPi-Distro/pi-gen#441]
The 2020-08-20 arm64 image [info files](https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2020-08-24/2020-08-20-raspios-buster-arm64-lite.info) state that the images were built from pi-gen commit 7252c154. That commit is not yet present in the GitHub repository.

**Comment by XECDesign** [comment]
The arm64 branch gets rebased sometimes. Aside from the hash, what's head of tree now should match what was released.
