### ISSUE TITLE
xz compression process needs memory limit (export-noobs breaks on certain hosts)

### ISSUE THREAD

**Issue by bamartin125** [RPi-Distro/pi-gen#479]
When running a build on a high core-count server, I run into an issue where the number of threads that xz attempts to use (56) effectively starves my machine for memory.

The configuration for xz for the number of threads to use is `-T0` and thus the number of threads and the amount of memory is unbounded by the definition given there and there is no way for the user to bound those parameters at run time through any configuration.

I suggest adding at least an `XZ_MEMLIMIT` or similar named configuration item with a fallback of 0 (infinity) which will allow a user to bound the memory taken by the process by configuration. If the config is not defined, the fallback will take place. The call could look like:

`xz -T0 --memlimit ${XZ_MEMLIMIT:-0}`

I also don't see a reason not to expose the number of cores to allow xz to use here as well. A configuration like `XZ_THREADS` could work?

`xz -T${XZ_THREADS:-0} --memlimit ${XZ_MEMLIMT:-0}`

I'll be following up with a pull request soon, but please let me know if I'm not on the right track here with my proposed solution thus far.

**Comment by XECDesign** [comment]
https://github.com/RPi-Distro/pi-gen/pull/480#issuecomment-1964305276
