### ISSUE TITLE
Repository needs to be updated for the 1/12 build

### ISSUE THREAD

**Issue by davesteele** [RPi-Distro/pi-gen#491]
There is a 1/12/21 Raspberry Pi OS build, using pi-gen commit 21090519. That commit is not present in this copy of the repository.

**Comment by davesteele** [comment]
Honest question - Is this intentional? If it is a deliberate strategy, I'll stop posting reminders.

**Comment by XECDesign** [comment]
I'll add tags to the release checklist, thank you.

**Comment by davesteele** [comment]
... and a push of the branch and tag. Thanks
