### ISSUE TITLE
Replacing bsdtar with libarchive-tools in README instruction

### ISSUE THREAD

**Issue by zhanghan177** [RPi-Distro/pi-gen#496]
Hi,

A similar issue has been raised in the Dockerfile: #428 

For this request, I'm suggesting to also update the README.md file to update `bsdtar` with another package, `libarchive-tools`. At least I need to make this change on Ubuntu 20.04 LTS. I'm not sure if this is a universal problem or only on newer distros.

**Comment by jimmy1248** [comment]
It is only an issue with newer distros. Debian Buster and Ubuntu Xenial are the only versions supported.

**Comment by amatsumara** [comment]
Yeah, building in Ubuntu 21.04: `tar --format gnu` seems to work well.

**Comment by XECDesign** [comment]
Should be fixed by https://github.com/RPi-Distro/pi-gen/commit/d562f2a35b8917cacab9a461626becbce424b652
