### ISSUE TITLE
Allow to enable serial cable in config file

### ISSUE THREAD

**Issue by grumpyf0x48** [RPi-Distro/pi-gen#503]
Just like we can enable `ssh` with:

`ENABLE_SSH=1`

It would be great to enable `serial` with:

`ENABLE_SERIAL=1`

or

`ENABLE_UART=1`

The config line to add in `boot/config.txt` is:

`enable_uart=1`

**Comment by XECDesign** [comment]
Looks like something that would be easy to do with a run file. In a chroot, run the relevant raspi-config command. I don't think the entire functionality of raspi-config needs to be made available through pi-gen's config.
