### ISSUE TITLE
bsdtar: Package bsdtar is not available. 

### ISSUE THREAD

**Issue by myxxmikeyxx** [RPi-Distro/pi-gen#512]
Package bsdtar is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libarchive-tools:i386 libarchive-tools

This is what I am getting from Ubuntu when trying to install the dependencies. 
Will libarchive-tools work instead?

**Comment by XECDesign** [comment]
Yes, the dependencies should be updated to use libarchive-tools, since that's the package bsdtar comes from. I believe bsdtar was a transitional package at some point.

**Comment by myxxmikeyxx** [comment]
Then the readme.md should be changed to
`apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip \
dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc \
qemu-utils kpartx`

**Comment by miccies3** [comment]
Hey, there was an update #526. I think the issue can be closed.
