### ISSUE TITLE
PIGEN_DOCKER_OPTS Default Case

### ISSUE THREAD

**Issue by DBongiorno-CG** [RPi-Distro/pi-gen#523]
#521 Introduced the PIGEN_DOCKER_OPTS, however there is no catch for the default docker build (i.e. PIGEN_DOCKER_OPTS is not specified).

#522 Seeks to set the default value of PIGEN_DOCKER_OPTS to "" within build-docker.sh

**Comment by XECDesign** [comment]
Thanks
