### ISSUE TITLE
debootstrap.log doesn't exist on failure

### ISSUE THREAD

**Issue by voltagex** [RPi-Distro/pi-gen#524]
See https://builds.sr.ht/~voltagex/job/527248, specifically

```
W: Failure trying to run: chroot "/home/build/pi-gen/work/2021-06-17-test/stage0/rootfs" /bin/true
W: See /home/build/pi-gen/work/2021-06-17-test/stage0/rootfs/debootstrap/debootstrap.log for details
rmdir: failed to remove '/home/build/pi-gen/work/2021-06-17-test/stage0/rootfs/debootstrap': Directory not empty
```

```
build@build:~/pi-gen$ less /home/build/pi-gen/work/2021-06-17-test/stage0/rootfs/build.log
/home/build/pi-gen/work/2021-06-17-test/stage0/rootfs/build.log: No such file or directory
```

https://github.com/RPi-Distro/pi-gen/blob/bf8c9f53833016e1b9410d2eb3ed0149390975a7/scripts/common#L25 doesn't seem like it should remove the file itself so I'm not sure what's going on.

**Comment by voltagex** [comment]
It's this, but I don't know why. 
https://github.com/RPi-Distro/pi-gen/issues/338

**Comment by voltagex** [comment]
seems to be a transient sr.ht failure.

**Comment by XECDesign** [comment]
It means debootstrap failed, so I'd check the log file it generates.

**Comment by XECDesign** [comment]
Sorry, missed the part where you mentioned the log file already.

I don't see pi-gen removing the log file. It tries to remove the directory and fails if it's not empty, which is the intended behaviour. On succesfull bootstrap, that directory should be empty.

Without being able to reproduce the issue myself, I can't really help.

**Comment by voltagex** [comment]
Right, the build system was unmounting things before I could check what was going on.

The underlying error appears to be

```
build@build:~$ sudo chroot "/home/build/pi-gen/work/2021-06-21-test/stage0/rootfs" /bin/true
chroot: failed to run command '/bin/true': Exec format error
```

Which I thought was handled by binfmt_misc and qemu-static.

**Comment by voltagex** [comment]
Sorry, I'd missed the `binfmt-support` package requirement. I still think there's a potential bug with the debootstrap.log being "hidden" in the now-unmounted filesystem.

**Comment by XECDesign** [comment]
What do you think would be an intuitive way to cope with that?

I didn't originally include qcow2 support was because it adds an extra layer of things that can go wrong and makes troubleshooting more difficult. Should the default be to not use qcow? Should pi-gen 'tail' the output of debootstrap.log if it's present?

**Comment by voltagex** [comment]
@XECDesign IMO qcow2 is the right thing to use, what about grabbing debootstrap.log and copying it out of the work path before unmounting?

**Comment by XECDesign** [comment]
Something along these lines?

https://github.com/RPi-Distro/pi-gen/commit/f9d44edb72e9a153c997266189c79cb1f96b69f3

**Comment by voltagex** [comment]
Thank you!

**Comment by nullromo** [comment]
I'm having the same error

`chroot: failed to run command ‘/bin/true’: Exec format error`

showing up in debootstrap.log. I don't understand what this means. @voltagex any info on how you solved this?

I could open a new issue if that's better.

**Comment by voltagex** [comment]
@nullromo no, this was 3 years ago. Exec format error means that the binary is the wrong type for your machine, i.e. arm binary trying to run on an x86_64 system.

**Comment by nullromo** [comment]
Thanks. I think I got confused about something, and I was running the wrong version of my code for a while there. I opened a [new issue](https://github.com/RPi-Distro/pi-gen/issues/782) instead.
