### ISSUE TITLE
Git log hangs

### ISSUE THREAD

**Issue by EdwardCooke** [RPi-Distro/pi-gen#530]
There is a commit from Micha(insert L character with a line through it) that is hanging my terminal when doing a git log. I have narrowed it down to the commit d562f2a35b8917cacab9a461626becbce424b652 that causes the problem. Anytime I paste the last character of his first name in to the terminal it causes it to lock up. I use Windows Terminal with the Debian distribution and Linux Subsystem for Windows. Is there anything you can do to the log history to fix it?

**Comment by XECDesign** [comment]
The log history is okay, this sounds like it should be reported here instead:

https://github.com/microsoft/terminal
