### ISSUE TITLE
Bugs in bullseye aarch64

### ISSUE THREAD

**Issue by Roethenbach** [RPi-Distro/pi-gen#538]
I had just build an bullseye image with branch arm64. openssh-server and sudo are not installed! So creating /boot/ssh has no effect. Furthermore automatic resizing of partitions seems not work. I've added openssh-server and sudo to 00-packages. Now an error after logging into system: "-bash: gettext.sh: File or directory not found". If possible: Please fix.

**Comment by XECDesign** [comment]
https://github.com/RPi-Distro/pi-gen/issues/504
