### ISSUE TITLE
Trouble building when "pi-gen/work" dir is not a symlink after fix has been applied

### ISSUE THREAD

**Issue by m-roberts** [RPi-Distro/pi-gen#54]
Git commit 40b5af925b8b00d2bd383358a4aa013c3367abc9 seems to be causing issues for me.

`➜  ~ git clone https://github.com/RPi-Distro/pi-gen`
Cloning into 'pi-gen'...
remote: Counting objects: 567, done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 567 (delta 20), reused 0 (delta 0), pack-reused 506
Receiving objects: 100% (567/567), 641.79 KiB | 302.00 KiB/s, done.
Resolving deltas: 100% (193/193), done.
Checking connectivity... done.
`➜  ~ cd pi-gen`
`➜  pi-gen git:(dev) sudo IMG_NAME="test" ./build.sh`
mkdir: missing operand
Try 'mkdir --help' for more information.

The problem seems to be that `WORK_DIR` is now returning empty:
```
export WORK_DIR=`readlink -f "${BASE_DIR}/work/${IMG_DATE}-${IMG_NAME}"`
```

This was a fix that was added for symlink support, but is now interfering with my ability to run pi-gen **without** a symlinked work directory.

**Comment by XECDesign** [comment]
That's what I get for pulling in PRs without testing them. Reverted.
