### ISSUE TITLE
Run stage or script as user

### ISSUE THREAD

**Issue by kleo** [RPi-Distro/pi-gen#542]
Is there way to use a stage or script as 'pi' or as another user? Or would it be just fine to do chown the directory as user?

**Comment by XECDesign** [comment]
You can use `sudo -u user command` in an `on_chroot` snippet. Otherwise, everything runs as root, so if all you need to do is chown a directory, you can do that without doing anything special.

**Comment by kleo** [comment]
Thank you!

**Comment by kleo** [comment]
I can't seem to do `sudo -u pi command` on my modified stage, `chown: invalid user: ‘pi’`
