### ISSUE TITLE
Build an image without the Internet? Using local copies of the needed parts...

### ISSUE THREAD

**Issue by capiman** [RPi-Distro/pi-gen#545]
Is it somehow possible or has someone tried out to build an image
with local copies of each part? 
At the moment I assume pigen downloads everything (again and again) from Internet during building.

**Comment by jketterl** [comment]
https://github.com/RPi-Distro/pi-gen/issues/539

**Comment by capiman** [comment]
Ok, many thanks for pointing me to the other entry!

**Comment by XECDesign** [comment]
We use apt-cacher-ng to prevent that. There are probably things other than apt that fetch things from the internet during build though, but there's usually some effort made to cache them.
