### ISSUE TITLE
/dev/nbd0 disconnected fails build

### ISSUE THREAD

**Issue by ivelin** [RPi-Distro/pi-gen#556]
Hello pi-gen team,

I am observing a new build error in my project's github action. Context [here](https://github.com/ambianic/ambianic-rpi-image/runs/4000353845?check_suite_focus=true#step:9:3939). 

This started happening recently. I tested with the scripts that worked fine for a pi-gen build a month ago. I don't see other related errors in the log. 

Would appreciate any pointers to the root cause. Thank you!

```
[18:00:30] Begin /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/stage2/03-set-timezone
[18:00:30] Begin /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/stage2/03-set-timezone/02-run.sh

Current default time zone: 'America/Chicago'
Local time is now:      Mon Oct 25 13:00:32 CDT 2021.
Universal Time is now:  Mon Oct 25 18:00:32 UTC 2021.

[18:00:33] End /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/stage2/03-set-timezone/02-run.sh
[18:00:33] End /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/stage2/03-set-timezone
/home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/stage2/rootfs: 10.4 GiB (11130044416 bytes) trimmed
/home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/stage2/rootfs/sys
/home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/stage2/rootfs/proc
/home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/stage2/rootfs/dev/pts
/home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/stage2/rootfs/dev
/home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/stage2/rootfs/boot
/home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/stage2/rootfs
/dev/nbd0 disconnected
[18:00:34] End /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/stage2
[18:00:34] Begin /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/pi-gen-stage-ambianic
Creating backing image: image-pi-gen-stage-ambianic.qcow2 <- /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/image-stage2.qcow2
Formatting '/home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/image-pi-gen-stage-ambianic.qcow2', fmt=qcow2 size=12884901888 backing_file=/home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/image-stage2.qcow2 cluster_size=65536 lazy_refcounts=off refcount_bits=16
read error, sector 0
mount: /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/work/rpi/pi-gen-stage-ambianic/rootfs: special device /dev/mapper/nbd0p2 does not exist.
[18:00:34] Unloading image
Error: Process completed with exit code 32.
```

**Comment by kleo** [comment]
I had much more reliable builds since building without qcow2 https://github.com/kleo/picroft/actions. I agree on switching it off

**Comment by ivelin** [comment]
> I had much more reliable builds since building without qcow2 https://github.com/kleo/picroft/actions. I agree on switching it off

Thank you for sharing. Could you please reference instructions or code how to switch off qcow2 in a custom rpi os build?

**Comment by ivelin** [comment]
> You can configure it at https://github.com/kleo/picroft/blob/main/config#L8
> 

Thank you for the pointer!

> PS: I love how you made the builder separated instead of adding the stage on a pi-gen fork like I previously did, it's much cleaner. Thank you!

The idea was to do less work in the future by not maintaining the fork, but obviously as we just experienced, there is higher risk than forking because the build breaks when the upstream code has a breaking change.

**Comment by ivelin** [comment]
Disabling qcow2 helped a bit as @kleo suggested. However stage2 of pigen [now breaks](https://github.com/ambianic/ambianic-rpi-image/runs/4167890549?check_suite_focus=true#step:9:2266) with:

```
Setting up iso-codes (4.2-1) ...
Setting up libgstreamer1.0-0:armhf (1.14.4-1) ...
unable to set CAP_SETFCAP effective capability: Operation not permitted
Setcap failed on gst-ptp-helper, falling back to setuid
Setting up cifs-utils (2:6.8-2) ...
update-alternatives: using /usr/lib/arm-linux-gnueabihf/cifs-utils/idmapwb.so to provide /etc/cifs-utils/idmap-plugin (idmap-plugin) in auto mode
Setting up libgstreamer-plugins-base1.0-0:armhf (1.14.4-2+deb10u1) ...
Setting up libdrm2:armhf (2.4.100-4+rpi1~bpo10+1) ...
Setting up libcamera0:armhf (0~git20211020+f4070274-1~bpo10~0) ...
Setting up libcamera-apps-lite (0~git20211021+2a38ae9-1~bpo10~0) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpt2+rpi1) ...
[16:37:52] End /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/stage2/01-sys-tweaks/00-packages-nr
[16:37:52] Begin /home/runner/work/ambianic-rpi-image/ambianic-rpi-image/pi-gen/stage2/01-sys-tweaks/00-packages
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python-is-python3
Error: Process completed with exit code 100.
```

Has anyone seen this and have a workaround to share?

Someone from the pigen team maybe? @XECDesign @samtygier @hhromic

**Comment by ivelin** [comment]
For the time being I reverted our built to [use the latest stable buster tag](
https://github.com/ambianic/ambianic-rpi-image/blob/ff95fe16847e75025399b6a87ea8f4cd22c07c16/.github/workflows/main.yml#L68):
```
git checkout tags/2021-05-07-raspbian-buster
```

**Comment by XECDesign** [comment]
Yup, if you're building something other than bullseye images, you'll probably run into trouble on the master branch.

**Comment by ivelin** [comment]
> Yup, if you're building something other than bullseye images, you'll probably run into trouble on the master branch.

Makes sense. 

I would suggest patching the [latest stable buster tag from May 2021](https://github.com/RPi-Distro/pi-gen/tree/2021-05-07-raspbian-buster) with @kleo 's [change](https://github.com/kleo/picroft/blob/main/config#L8
) (`USE_QCOW2=0`). Otherwise buster builds break as we reported above.

**Comment by XECDesign** [comment]
Tags are meant to match what was actually released, but I could cherry-pick https://github.com/RPi-Distro/pi-gen/commit/68fee340f95eb630a706e2dbf75615c6be4e980b into the buster branch.

**Comment by ivelin** [comment]
Right. I was suggesting a new tag with this patch. Cherry picking [68fee34](https://github.com/RPi-Distro/pi-gen/commit/68fee340f95eb630a706e2dbf75615c6be4e980b) seems to make sense.

**Comment by marcone** [comment]
> Yup, if you're building something other than bullseye images, you'll probably run into trouble on the master branch.

Would it make sense to update the README.md in master then, since that still says that you can build jessie, stretch and buster.

**Comment by XECDesign** [comment]
> Would it make sense to update the README.md in master then, since that still says that you can build jessie, stretch and buster.

Yeah, I will do that after the next image release. Thanks
