### ISSUE TITLE
E: Unable to locate package libcamera-apps-lite

### ISSUE THREAD

**Issue by myxxmikeyxx** [RPi-Distro/pi-gen#565]
When I tried to run pi-gen it got to stage2 then failed because it says its cant find libcamera-apps-lite package.
Do I need to add a repository or raspberry pi repository?

**Comment by XECDesign** [comment]
It comes from this repo: http://archive.raspberrypi.org/debian/ (buster and bullseye).

And it's enabled here: https://github.com/RPi-Distro/pi-gen/blob/master/stage0/00-configure-apt/00-run.sh#L6

**Comment by myxxmikeyxx** [comment]
I assume these are from buster and bullseye too 
`E: Unable to locate package python-is-python3
E: Unable to locate package rpi-eeprom
E: Unable to locate package raspinfo`

And thank you.

**Comment by myxxmikeyxx** [comment]
I figured out my problem, thank you

**Comment by XECDesign** [comment]
Yes. I think getting a reasonable build that's not bullseye is probably going to take a few modifications.

**Comment by myxxmikeyxx** [comment]
yes I am going to try the jessie branch.

**Comment by myxxmikeyxx** [comment]
do you have a stretch branch or just tags

**Comment by XECDesign** [comment]
just tags, I didn't make a branch for it at the time.

**Comment by myxxmikeyxx** [comment]
> just tags, I didn't make a branch for it at the time.

:+1:

**Comment by pirateradiohack** [comment]
I also get the `Unable to locate package python-is-python3` when trying to build buster. @myxxmikeyxx when you say you figured out your problem, would you tell me how you solve it? Thanks.
