### ISSUE TITLE
ARM64 Build Setarch Linux 32

### ISSUE THREAD

**Issue by luigifcruz** [RPi-Distro/pi-gen#572]
In the ARM64 branch, there is a command to run `on_chroot` with the `setarch linux32` modifier. This causes GCC `-mtune=native` to freak out. The `arch` command also returns `armv8l` instead of the usual `arm64`. These flags can cause build errors because of the `+nofp+nosimd` flags. Is there any particular reason why the `setarch linux32` is still there?

With `setarch linux32`:
```
The following options are target specific:
  -mabi=                      		lp64
  -march=                     		armv8-a+crypto+crc+nofp+nosimd
```

Without:
```
The following options are target specific:
  -mabi=                      		lp64
  -march=                     		armv8-a+crypto+crc
```

**Comment by XECDesign** [comment]
> Is there any particular reason why the `setarch linux32` is still there?

No, that sounds like the opposite of the behaviour you'd want. Working with an armhf userland with an arm64 kernel can cause issues where some software gets confused about its architecture (which is what `setarch` is for).

Thanks for spotting this.
