### ISSUE TITLE
64 bit image

### ISSUE THREAD

**Issue by ThirtySomething** [RPi-Distro/pi-gen#580]
Hi there,

is it somehow possible to build an image of a 64 bit Raspi OS? A 64 bit version of Raspi OS is available [here](https://downloads.raspberrypi.org/raspios_arm64/). During my tests I was not able to find some kind of switch to select between the usual 32 bit version and the new 64 bit version.

Regards

ThirtySomething

**Comment by XECDesign** [comment]
Yup, it's built from the arm64 branch. Merging it so that everything is built from one branch is on the todo list.

**Comment by ThirtySomething** [comment]
@XECDesign That's great, so I'm still waiting.

**Comment by XECDesign** [comment]
Not sure what there's to wait for. The branch is and has been available to use for a long time.

**Comment by ThirtySomething** [comment]
@XECDesign I'm sorry - there was a misunderstanding from my side. I've expected this in the same script, not in a different branch. Now it's clear from my side. Thanks for pushing me in the right direction.

**Comment by maxpavlov** [comment]
Hey. Just a quick on for 2023 - if one wants to build a 64bit image, the arm64 branch should be used still, right? If an image is created based on the sources from the master branch, it will be for 32bit OS, correct? Thanks :)

**Comment by XECDesign** [comment]
That's right
