### ISSUE TITLE
Do I need to crosscompile files from source?

### ISSUE THREAD

**Issue by rafaelrojasmiliani** [RPi-Distro/pi-gen#582]
First of all, I would like to congratulate the contributors of this project. It is great.

I would like to build custom images that contains packages that must be compiled.
However, it is not clear to me when I compile using `chroot` inside some stage I'm actually compiling to ARM.
Do someone knows if this is true?

**Comment by XECDesign** [comment]
While you can compile software inside the chroot, it would probably make more sense for pi-gen to install pre-built binaries or .deb files.

**Comment by rafaelrojasmiliani** [comment]
Yes you're right. But there are not deb packages for the software I need :(

**Comment by XECDesign** [comment]
If that's the only way and you can't pre-compile the binaries beforehand, that's fair.

Yeah, to confirm, if you build something in the chroot, it will build for ARM. However, the currently released versions of qemu all have their own set of problems which may make this approach unreliable. Should be fine for software that's not too complicated.

**Comment by rafaelrojasmiliani** [comment]
Thanks! this answer my question!
