### ISSUE TITLE
How to Generate 64 bit OS for debian

### ISSUE THREAD

**Issue by kutchu** [RPi-Distro/pi-gen#585]
Hi Team, Could you please help me out how can i create a 64 bit OS image on Mac? I have cloned the repo and through master branch it generates a 32 bit OS. I have read that recent [release](https://www.xda-developers.com/raspberry-pi-os-64-bit/) is also supporting 64 bit OS.

**Comment by clarkchentw** [comment]
arm64 branch has the code for 64 bits compilation
