### ISSUE TITLE
arm64 build could use http_proxy

### ISSUE THREAD

**Issue by gromain** [RPi-Distro/pi-gen#598]
The line here can be uncommented:
https://github.com/RPi-Distro/pi-gen/blob/255288909beae446a4f1eeedaa544f1a7d421e54/scripts/common#L10

debootstrap seems to work well this this now.

Just creating this issue to track this change.

_Originally posted by @gromain in https://github.com/RPi-Distro/pi-gen/issues/595#issuecomment-1047286431_

**Comment by XECDesign** [comment]
Seems to work in my testing as well. Thanks.
