### ISSUE TITLE
Printing "Done! Your image(s) should be in deploy/" after failure

### ISSUE THREAD

**Issue by volym3ad** [RPi-Distro/pi-gen#60]
After build fails to create raspbian image, pi-gen no matter prints that image should be in deploy/ folder. This is a small bug, but it is annoying when your build fails and you must look into deploy folder expecting that image is there... But it's not true =)

**Comment by XECDesign** [comment]
Yes, error handling is almost non-existent. I am thinking a python port in the future with better error handling would be nice, but it would have to be something I'd do in my spare time.

**Comment by XECDesign** [comment]
Let's call this a duplicate of #64
