### ISSUE TITLE
install: target '/pi-gen/work/2022-04-15-Raspbian/stage0/rootfs/etc/apt/' is not a directory: No such file or directory

### ISSUE THREAD

**Issue by jerrychong25** [RPi-Distro/pi-gen#610]
Hi all,

I'm facing some compilation issue on generating own Raspbian Image.

After run build command, apparently it hits following error:

`install: target '/pi-gen/work/2022-04-15-Raspbian/stage0/rootfs/etc/apt/' is not a directory: No such file or directory`

Here is the error screenshot:
<img width="952" alt="Screenshot 2022-04-15 at 12 29 02 AM" src="https://user-images.githubusercontent.com/15714095/163572661-8edd09e2-f056-4b82-8ef4-08fbe71577ec.png">

Environment:
- macBook Pro 2021 14 inch Apple M1 Pro Chip
- macOS Monterey

Is there any alternative/solution to make it work on this environment? 

If not, what is the best alternative solution (Ubuntu/Debian) to build the same image?

This issue is quiet similar to: 
- https://github.com/RPi-Distro/pi-gen/issues/340
- https://github.com/RPi-Distro/pi-gen/issues/276

Thanks in advance!

**Comment by XECDesign** [comment]
That's not an environment I'd expect things to work on. I don't have access to the appropriate hardware to investigate how to make it work.

I would recommend building natively on a pi under Raspberry Pi OS with a sufficiently large storage medium.

**Comment by jerrychong25** [comment]
> That's not an environment I'd expect things to work on. I don't have access to the appropriate hardware to investigate how to make it work.
> 
> I would recommend building natively on a pi under Raspberry Pi OS with a sufficiently large storage medium.

Hi @XECDesign ,

Noted, I will try again on my end for Raspberry Pi 4 directly.

**Comment by jerrychong25** [comment]
Managed to build same code in Pi 4 Firmware v1.5, will close this issue

Thanks @XECDesign !

**Comment by thk686** [comment]
I have just encountered this using build-docker.sh on osx.
