### ISSUE TITLE
Building pi-gen with vagrant

### ISSUE THREAD

**Issue by pirateradiohack** [RPi-Distro/pi-gen#619]
I have used different methods to build pi-gen from my workstation (Arch Linux, intel 64bits). But as of late, even the docker method is failing for me.
I was recommended in another issue to try a virtual machine with an OS listed in the supported list: Debian Buster or Ubuntu Xenial.
I tried and it seems to work. In order to streamline the experience I find vagrant quite straightforward.

Here is my Vagrantfile for anyone interested:

```
Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-buster64"

  config.vm.synced_folder ".", "/pigen"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip \
    dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc \
    qemu-utils kpartx gpg pigz
  SHELL
end
```
When this file is at the root of the pi-gen repo it shares your local folder with pi-gen repo on the VM in `/pigen`.
It means you just need to run the following commands in order to build:
- `vagrant up`
- `vagrant ssh --command 'sudo /pigen/build.sh'`
- `vagrant halt`

And if all goes well you should see your newly built image appear in your local `deploy` folder.

If you would like me to do a PR with that file and the instructions on how to use it in the README just let me know and I'll take care of that. If not, feel free to close the issue.

**Comment by XECDesign** [comment]
I'm not sure. Vagrant is definitely a much better option than Docker, but I don't want to add 100 different containerisation and virtualisation alternatives I don't use and can't support.

**Comment by pirateradiohack** [comment]
Sure, that's why I did not do a PR straight away. 

Let's leave that in the ticket then, and I will update it if I find some improvements and will help if I can.

Meanwhile I'll go ahead and close it.
