### ISSUE TITLE
Repeated use of build-docker.sh eats disk space extremely fast

### ISSUE THREAD

**Issue by malaire** [RPi-Distro/pi-gen#62]
Each use of `build-docker.sh` leaves behind tens of GBs of files in `/var/lib/docker` which are never deleted, not even with `docker rm pigen_work`.

This eats up disk space extremely fast, wasting easily hundreds of GB, with no way to get rid of these files (except `sudo rm -rf` which might destroy integrity of docker).

**Comment by andrewmichaelsmith** [comment]
@malaire I think you want to do:

`docker rm -v pigen_work`

**Comment by XECDesign** [comment]
Fixed by https://github.com/RPi-Distro/pi-gen/pull/70
