### ISSUE TITLE
WPA_COUNTRY is not added to /etc/wpa_supplicant/wpa_supplicant.conf

### ISSUE THREAD

**Issue by kirilllivanov** [RPi-Distro/pi-gen#631]
Hi!
This code does not add `country=` to the file `/etc/wpa_supplicant/wpa_supplicant.conf`.
https://github.com/RPi-Distro/pi-gen/blob/bd85d61c055a23a747c718741b25d3a0c0a7fbef/stage2/02-net-tweaks/01-run.sh#L11-L15

If I run `raspi-config nonint do_wifi_country US` manually, then the line `country=US` is added to the file.
I am using Docker to build the image.

**Comment by XECDesign** [comment]
That line should no longer be required, as the `crda` package contains another mechanism for setting the wifi country (`/etc/default/crda`).

Since we want to support NetworkManager as well, needed to move to a more generic regdom setup method.
