### ISSUE TITLE
Is it somehow already possible to switch from kernel 5.15.61 to 5.19?

### ISSUE THREAD

**Issue by capiman** [RPi-Distro/pi-gen#637]
In the past we learnt about a security leak which seems it was fixed in 5.19 (don't know if backported to 5.15.x).
And today we found an error with Bluetooth which seems to be fixed with 5.17.
So anything newer than 5.17 would be helpful...

**Comment by XECDesign** [comment]
That's not a feature of pi-gen, no. But, if you know what you're doing you could provide a custom kernel.

**Comment by capiman** [comment]
Thanks for your answer! In general I know how to compile a kernel.
Do you know where I can get all the switches which were used to compile a kernel, so I can use similar ones to the provided one?

**Comment by XECDesign** [comment]
This should give you something very close to the official kernel:

https://www.raspberrypi.com/documentation/computers/linux_kernel.html
