### ISSUE TITLE
How to install a systemd service for the first user?

### ISSUE THREAD

**Issue by jedahan** [RPi-Distro/pi-gen#660]
Now that Raspberry Pi OS does not come with a default pi user, what is the correct way to add a user service to a pi-gen build? Is there any way to hook into the Raspberry Pi Imager first user?

Thanks

**Comment by j123b567** [comment]
You can create a user service in `/usr/lib/systemd/user/` or in `/etc/systemd/user/` and later enable it for all users using `systemctl --global enable`, if you don't mind running it for all logged in users (you will probably have only one user on the target system anyway).

**Comment by jedahan** [comment]
thank you
