### ISSUE TITLE
linux-perf package is 5.10 from Debian, but Raspberry Pi kernel is 5.15.

### ISSUE THREAD

**Issue by JinShil** [RPi-Distro/pi-gen#662]
Forgive me if this is not the right place to report this, but there is a version mismatch that prevents installing `linux-perf` for the current release of the Raspberry Pi OS.  

The Raspberry Pi OS is on kernel version 5.15, but Debian is on kernel version 5.10. Therefore, when one tries to run `sudo apt install linux-perf` it installs `linux-perf-5.10`.  Then when running `perf` it fails with `/usr/bin/perf: line 13: exec: perf_5.15: not found`.

Please consider adding a `linux-perf` package that matches the Raspberry Pi kernel version to the Raspberry Pi repository.

**Comment by XECDesign** [comment]
This will be part of the work of migrating away from the raspberrypi-firmware package to upstream debian ones where possible. Aiming to have that done for the Bookworm release.

**Comment by JinShil** [comment]
This appears to have been resolved.
