### ISSUE TITLE
ppromt marked as executable causing warning message in journalctl logs

### ISSUE THREAD

**Issue by JinShil** [RPi-Distro/pi-gen#663]
Run `journalctl` after first boot and you'll see this warning message:

```
systemd-xdg-autostart-generator[537]: Configuration file /etc/xdg/autostart/pprompt.desktop is marked executable. Please remove executable permission bits. Proceeding anyway.
```

It's probably benign, but it's always nice to keep the logs tidy.

**Comment by spl237** [comment]
Fixed.

**Comment by XECDesign** [comment]
Updated package should go live later today. It will fix the issue for future Raspberry Pi OS images, but not existing installs.
