### ISSUE TITLE
How do you use this tool?

### ISSUE THREAD

**Issue by JamesPi123** [RPi-Distro/pi-gen#67]

**Comment by Landrash** [comment]
Read the [Read Me](https://github.com/RPi-Distro/pi-gen/blob/dev/README.md).
It requires some Linux knowledge and is not a end user tool.

**Comment by redjaguar** [comment]
The Read Me gives basic usage. It is not comprehensive in the entire structure.. Using it requires bash/sh scripting knowledge to decipher a lot of what is actually going on.
