### ISSUE TITLE
How do I build for x64?

### ISSUE THREAD

**Issue by Awire9966** [RPi-Distro/pi-gen#707]
I want to build [this](https://www.raspberrypi.com/software/raspberry-pi-desktop) but in a 64 bit version for my 64 bit PCs.

**Comment by barneyman** [comment]
https://github.com/RPi-Distro/pi-gen#64-bit-systems

**Comment by Awire9966** [comment]
@barneyman 
I mean the x86_64 not ARM64

**Comment by XECDesign** [comment]
That's not currently something we support.
