### ISSUE TITLE
Commit has broken using "PRESERVE_CONTAINER=1 CONTINUE=1" on arm64 branch docker builds

### ISSUE THREAD

**Issue by cjcdev** [RPi-Distro/pi-gen#709]
This pull request:
https://github.com/RPi-Distro/pi-gen/pull/705

Has broken the ability to use "PRESERVE_CONTAINER=1 CONTINUE=1" on docker builds (not removing the container).

**Comment by XECDesign** [comment]
Did https://github.com/RPi-Distro/pi-gen/pull/716 fix it or was that only a partial fix?

**Comment by cjcdev** [comment]
@XECDesign Yes, #716 fixed the issue.  Thank you!

Unrelated - is there a way to build "bullseye" from the latest arm64 branch?  I believe this is not working.

**Comment by cjcdev** [comment]
Closing because it was resolve by https://github.com/RPi-Distro/pi-gen/pull/716
