### ISSUE TITLE
[Feature Request] `Raspberry Pi reference` text hard-coded in `issue.txt`

### ISSUE THREAD

**Issue by stefanb2** [RPi-Distro/pi-gen#719]
`scripts/common` hard-codes the text `Raspberry Pi reference` in `issue.txt`:

~~~sh
update_issue() {
	echo -e "Raspberry Pi reference ${IMG_DATE}\n..." > "${ROOTFS_DIR}/etc/rpi-issue"
}
~~~

While this is true for official builds from Raspberry Pi, it is technically not correct for builds with tailored configurations generated from clones of [RPi-Distro/pi-gen](https://github.com/RPi-Distro/pi-gen).

It would be nice if this text could be overridden with a new variable in `config`, e.g. `RELEASE_NAME`.

I'm happy to provide a PR if we can agree on the naming & implementation.

**Comment by XECDesign** [comment]
No objections from me. As long as the new feature is documented in the README and the  default behaviour doesn't change, I'll accept a PR.
