### ISSUE TITLE
The build date is always UTC, even with different time zone settings

### ISSUE THREAD

**Issue by g-e-r** [RPi-Distro/pi-gen#72]
This took me some time to find out.
 My timezone - PDT - is UTC-7
 So if I start a build and it fails after 5pm, the date will change...
 That happens very often in the US West coast.
 there should be a better strategy for this.

**Comment by thomas-phillips-nz** [comment]
In build.sh, line 131, it assigns the `IMG_DATE` variable to the current UTC date _if the IMG_DATE variable is not set_. You should be able to invoke the script using IMG_DATE=xxx ./build.sh if you want to set your own date.

That said, I don't like the fact that the date is UTC either. I propose we change it to always use local system time. It can always be overridden using the IMG_DATE variable.

**Comment by XECDesign** [comment]
Fixed by https://github.com/RPi-Distro/pi-gen/pull/77
