### ISSUE TITLE
Please do not default to using Google nameservers

### ISSUE THREAD

**Issue by geromueller** [RPi-Distro/pi-gen#73]
See discussion here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761658

**Comment by blacktigersoftware** [comment]
very interesting read.  

I agree - but for different reasons.  

Having a default nameserver means that misconfigurations may go unnoticed. example:  "I can't see the machine right next to me, but I can get web-pages, so what's wrong????"   -- vs -- "I can't see the machine next to me and I can't resolve web pages, so what's wrong????"  Debian maintainer was put off with the 'privacy' and 'google' aspect.  I suspect a properly configured machine would never have to resort to the default.  And if it did, you would never know that is was not configured correctly and instead chase some other problem.

**Comment by Landrash** [comment]
It's a bad plan forking more things than necessary for Raspbian.
The pi-gen code is forkable and you can just change what you prefer when you make your own images.

**Comment by XECDesign** [comment]
Closing due to the same objections as those raised in the linked bug report. We may revisit this later.
