### ISSUE TITLE
Removal of config.txt symlinks breaks postinst for fbturbo package

### ISSUE THREAD

**Issue by SimonHyde-BBC** [RPi-Distro/pi-gen#756]
The change in a125344 breaks the postinst scripts for xserver-xorg-video-fbturbo which still check the contents of /boot/config.txt

**Comment by XECDesign** [comment]
Wish I got around to this earlier, because this change just tripped me up as well.

Since fbturbo no longer works in the only world we support (kms), I've modified fbturbo to be disabled by default.
