### ISSUE TITLE
When building an image with zfs-dkms and DEBIAN_FRONTEND=noninteractive and still getting confirmation window

### ISSUE THREAD

**Issue by VeloAddict** [RPi-Distro/pi-gen#758]
In stage 2 00-packages I added : `zfs-dkms zfsutils-linux`.
In config I added `DEBIAN_FRONTEND=noninteractive`
Started a build. I was not expecting this:
<img width="1735" alt="SCR-20240228-rutw" src="https://github.com/RPi-Distro/pi-gen/assets/36549/841e58ad-5cf0-49cc-a582-a8b577f57cc5">

What can I do to now have to interact with that prompt?

**Comment by VeloAddict** [comment]
I also tried running this in on_chroot:
`DEBIAN_FRONTEND=noninteractive apt install zfs-dkms zfsutils-linux`

But got the same result.

**Comment by VeloAddict** [comment]
I figured it out.
In `00-debconf` I added:
`zfs-dkms zfs-dkms/note-incompatible-licenses note true`

Maybe this will be helpful for others.

**Comment by VeloAddict** [comment]
I figured it out.
In 00-debconf I added:
zfs-dkms zfs-dkms/note-incompatible-licenses note true

Maybe this will be helpful for others.

**Comment by XECDesign** [comment]
Thanks for posting the solution for others
