### ISSUE TITLE
The apt caching proxy we use currently is unreliable - let's replace it with nginx?

### ISSUE THREAD

**Issue by abdullah-kasim** [RPi-Distro/pi-gen#762]
The apt caching proxy we use, which is `apt-cacher-ng` is unreliable and we should replace it with something else - most likely nginx.

Across various websites and on my local testing, apt-cacher-ng has been quite unreliable for caching. I'd get 502 errors that I'd never get with direct connections.

There's this [reddit post](https://old.reddit.com/r/debian/comments/klebea/psa_aptcacherng_is_a_buggy_pile_of_shit/) that has compiled places on where to look for apt-cacher-ng issues. and my experience is similar.

There's a config file at this [reddit post](https://old.reddit.com/r/linuxadmin/comments/179zm4a/aptcacherng_not_working_lately_503_errors/) that promises to fix everything - alas, I'm still facing the same 502 errors with the config file suggested.

I gave up on apt-cacher-ng after spending 3 half-days on it, and decided to try squid and nginx instead. SQUID is a no-go, as it doesn't cache 302, so I tried nginx afterwards - which requires a bit more settings and I'm not too great with nginx. Still, I spent a lot less time on it than I did with apt-cacher-ng or SQUID.

Anyway, here's what I got. By using nginx, I've made, hopefully, the perfect apt caching proxy server. The [config](https://github.com/RPi-Distro/pi-gen?tab=readme-ov-file#config) instruction for APT_PROXY requires no change - this is a drop-in compatible change.

<project-root>/docker-compose.yml

```yml
# <project-root>/docker-compose.yml
version: '3.8'
services:
  cache:
    image: nginx:1.25.4-bookworm # lock the version in to prevent docker compose from failing months later.
    ports:
      - '3142:3142'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - cache:/var/cache/nginx

volumes:
  cache:
```

<project-root>/nginx.conf

```nginx
# <project-root>/nginx.conf
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=100g inactive=365d use_temp_path=off;

    log_format proxied '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    'Cache: $upstream_cache_status';

    access_log /dev/stdout proxied;

    server {

        listen 0.0.0.0:3142;

        resolver 127.0.0.11;

        location / {

            resolver 127.0.0.11;

            proxy_pass http://$http_host$uri$is_args$args;
        }

        location ~* \.(deb|xz)$ {

            resolver 127.0.0.11;

            proxy_cache my_cache;
            proxy_cache_valid 200 365d;
            proxy_cache_valid 302 365d;
            proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
            proxy_cache_background_update on;
            proxy_cache_revalidate on;

            proxy_pass http://$http_host$uri$is_args$args;

        }

    }

    include /etc/nginx/conf.d/*.conf;
}

```

**Comment by XECDesign** [comment]
For me, the main priority for pi-gen is to build the official Raspberry Pi OS images. apt-cacher-ng has been rock solid for many years for this purpose, so I'm not inclined to change anything in that area.

Of course APT_PROXY can be set to anything and handled by anything. apt-caher-ng is just an example. If anything, I think fe45b739871c2eba65ec520e00816299abbfbc5b should probably be reverted altogether, since it references a random docker container that we can't vouch for.
