### ISSUE TITLE
stage_list availability during build

### ISSUE THREAD

**Issue by knachte** [RPi-Distro/pi-gen#763]
The config file contains an entry "stage_list" that tells the build systems what steps to perform, however this variable is not exported in build.sh. Is there any way to know in a certain stage which build stages are requested? 
I could do an export of stage list in build.sh, but first wanted to check if there is something i'm missing.

**Comment by XECDesign** [comment]
If you believe it would be useful, I wouldn't mind accepting a PR with the change.

**Comment by knachte** [comment]
I just sent the pr, it got pushed back a bit due to embedded world.
