### ISSUE TITLE
stage2/02-net-tweaks/01-run.sh

### ISSUE THREAD

**Issue by AZincenco** [RPi-Distro/pi-gen#779]
Hello

The script stage2/02-net-tweaks/01-run.sh has a typo in line 6: `if [ -v WPA_COUNTRY ]; then`
it should be
`if [ -v "${WPA_COUNTRY}" ]; then`
Hope it helps

**Comment by XECDesign** [comment]
From the documentation for bash:
>        -v varname
>              True if the shell variable varname is set (has been assigned a value).

Checking that it works as intended:
```
$ if [ -v TEST ]; then echo "TEST is set to $TEST"; else echo "TEST is unset"; fi
TEST is unset
$ TEST=something; if [ -v TEST ]; then echo "TEST is set to $TEST"; else echo "TEST is unset"; fi
TEST is set to something
```
