### ISSUE TITLE
How do I make an image that only contains Stage 0 Stage 1 Stage 2 Stage 3?

### ISSUE THREAD

**Issue by TopgunZh** [RPi-Distro/pi-gen#819]
I don’t need Stage 4 because I can’t use many of its softwares. 
I use the "touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES" and "sudo ./build.sh" cmd，I can  only generate a lite image.

How should I configure？

**Comment by TopgunZh** [comment]
> Hi, I thing you must add a `SKIP` file in stage you don't want, e.g. :
> 
> ```
> touch ./stage4/SKIP ./stage5/SKIP
> touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES
> ```
> 
> https://github.com/RPi-Distro/pi-gen/blob/master/README.md#stage-specification

No, I tried it, but it can only generate a lite image.

**Comment by plmorange** [comment]
You want to generate an image for the stage 4 or 5 or only a lite one ?

**Comment by TopgunZh** [comment]
> You want to generate an image for the stage 4 or 5 or only a lite one ?
I've found a way. Thanks.
