### ISSUE TITLE
Building an image with Stretch

### ISSUE THREAD

**Issue by guysoft** [RPi-Distro/pi-gen#88]
Hey,
Is there a way to make pi-gen build Stretch?

Update:
I guess it might work if you pass this as a variable?
https://github.com/RPi-Distro/pi-gen/blob/dev/stage0/prerun.sh

Thanks

**Comment by nickfox-taterli** [comment]
no,raspbian source list and raspi list must be modify too,and more packages name are differnent.

**Comment by guysoft** [comment]
Ok, is there a location where this is discussed?
Is there a new branch planned or something like that?

**Comment by nickfox-taterli** [comment]
I was build Stretch at 3 hours ago,but something are not stable, modify file patch : https://github.com/nickfox-taterli/pi-gen-chinese/commit/250203562db756bad53f65eb4f6cb1a11c4efd7a

**Comment by guysoft** [comment]
Is https://github.com/nickfox-taterli/pi-gen-chinese a fork?
Or its a repo you generated?

**Comment by nickfox-taterli** [comment]
I made a lot of changes to fit the CN GFW network environment only, so I created a new repo. But pi-gen features did not change much.

**Comment by XECDesign** [comment]
Should be good now.

**Comment by guysoft** [comment]
I see the move was done on https://github.com/RPi-Distro/pi-gen/commit/8f361a1c38f0cc00d7a04486a93b2fe29f67ee5c

You pushed this from an internal repo?

**Comment by XECDesign** [comment]
yes

**Comment by guysoft** [comment]
So you committed the stuff on Jul 19, 23 days before this issue was opened, but pushed it only yesterday?
We could have been testing this for a month.

**Comment by XECDesign** [comment]
Pretty sure there has already been a discussion about releasing stuff before it's ready.

**Comment by guysoft** [comment]
I've been talking about this here for a while with jamesh:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=187797&p=1183905#p1183905
I would value your input, I don't want to step on someones feet by mistake. There is an understandable clash of interests here I don't want it to be taken the wrong way.

**Comment by XECDesign** [comment]
posted a reply (as shiftplusone)
