### ISSUE TITLE
Local proxy and  apt-cacher-ng

### ISSUE THREAD

**Issue by anderson-** [RPi-Distro/pi-gen#92]
Hi, I'm trying to use build-docker.sh using apt-cacher-ng. I installed apt-cacher-ng and didn't changed its default settings, and needless to say, it didn't work :disappointed: Do you have some more info in how to setup it? Thanks! :smile:

**Comment by XECDesign** [comment]
Check the bit about using docker with apt-cacher-ng in the config section here:
https://github.com/RPi-Distro/pi-gen#config

Does that help?
